# Combined Heuristic

* 引入本项目所需程序包

In [53]:
import numpy as np
import timeit

* 读取picker location数据

In [54]:
# loadtxt, 明确指定每列数据的类型
filename = './picker location.txt'
picker_location = np.loadtxt(filename,  #文件名
                        dtype=int)      #数据类型
print picker_location, picker_location.shape

[[ 3  7  4]
 [ 1  3  9]
 [ 3  7  3]
 [ 2  9  2]
 [ 3 14  6]
 [ 4 14 11]
 [ 1 14 10]
 [ 3 11  1]
 [ 2  6  9]
 [ 4  2  1]
 [ 4  7  4]
 [ 2 16  3]
 [ 4 17  9]
 [ 2  3  1]
 [ 3  2  9]
 [ 2 17  8]
 [ 3 15  1]
 [ 1 12  1]
 [ 3 12  8]
 [ 4  6  8]
 [ 3  3  5]
 [ 4 13  4]
 [ 1  3  2]
 [ 2 12  7]
 [ 1  4  2]
 [ 1 17  4]
 [ 2 13 10]
 [ 1  1  6]
 [ 2  1  3]
 [ 2  8  4]
 [ 1  3  6]
 [ 3  9  1]
 [ 4 16  2]
 [ 1  3  4]
 [ 3  5 11]
 [ 4 17 11]
 [ 1  6  7]
 [ 4 10  5]
 [ 2 14 10]
 [ 1 12  8]
 [ 4  6  4]
 [ 4  7 11]
 [ 2  7  2]
 [ 4 12  5]
 [ 3  6  6]
 [ 2 10  1]
 [ 2  3  5]
 [ 3  4  7]
 [ 3  1  3]
 [ 1  8  1]
 [ 4  9  3]
 [ 3 16  1]
 [ 1 10  6]
 [ 3 11  5]
 [ 4  8  4]
 [ 3  5 11]
 [ 4 11 11]
 [ 3 11  6]
 [ 1 12  3]
 [ 2  8  8]
 [ 2  9  3]
 [ 2 13  4]
 [ 3 18 12]
 [ 2 10  8]
 [ 1 14  9]
 [ 2  5  3]
 [ 1 14 10]
 [ 1 12  6]
 [ 2  8  6]
 [ 2  3  7]
 [ 4 13  5]
 [ 1 17  6]
 [ 4  2 11]
 [ 3  7  8]
 [ 1 10  9]
 [ 1  7  1]
 [ 2  4  8]
 [ 3 11  9]
 [ 3  7  5]
 [ 4  7  5]
 [ 3  3  9]
 [ 3 17  6]
 [ 1  6  8]
 [ 3

* 读取包含前侧和后侧决策点的所有位置数据

In [55]:
# loadtxt, 明确指定每列数据的类型
filename = './AllLocation.csv'
All_location = np.loadtxt(filename,         #文件名
                          delimiter=',',    #分割符
                          dtype=int         #数据类型
                         )  
print All_location, All_location.shape

[[ 3  7  4]
 [ 1  3  9]
 [ 3  7  3]
 [ 2  9  2]
 [ 3 14  6]
 [ 4 14 11]
 [ 1 14 10]
 [ 3 11  1]
 [ 2  6  9]
 [ 4  2  1]
 [ 4  7  4]
 [ 2 16  3]
 [ 4 17  9]
 [ 2  3  1]
 [ 3  2  9]
 [ 2 17  8]
 [ 3 15  1]
 [ 1 12  1]
 [ 3 12  8]
 [ 4  6  8]
 [ 3  3  5]
 [ 4 13  4]
 [ 1  3  2]
 [ 2 12  7]
 [ 1  4  2]
 [ 1 17  4]
 [ 2 13 10]
 [ 1  1  6]
 [ 2  1  3]
 [ 2  8  4]
 [ 1  3  6]
 [ 3  9  1]
 [ 4 16  2]
 [ 1  3  4]
 [ 3  5 11]
 [ 4 17 11]
 [ 1  6  7]
 [ 4 10  5]
 [ 2 14 10]
 [ 1 12  8]
 [ 4  6  4]
 [ 4  7 11]
 [ 2  7  2]
 [ 4 12  5]
 [ 3  6  6]
 [ 2 10  1]
 [ 2  3  5]
 [ 3  4  7]
 [ 3  1  3]
 [ 1  8  1]
 [ 4  9  3]
 [ 3 16  1]
 [ 1 10  6]
 [ 3 11  5]
 [ 4  8  4]
 [ 3  5 11]
 [ 4 11 11]
 [ 3 11  6]
 [ 1 12  3]
 [ 2  8  8]
 [ 2  9  3]
 [ 2 13  4]
 [ 3 18 12]
 [ 2 10  8]
 [ 1 14  9]
 [ 2  5  3]
 [ 1 14 10]
 [ 1 12  6]
 [ 2  8  6]
 [ 2  3  7]
 [ 4 13  5]
 [ 1 17  6]
 [ 4  2 11]
 [ 3  7  8]
 [ 1 10  9]
 [ 1  7  1]
 [ 2  4  8]
 [ 3 11  9]
 [ 3  7  5]
 [ 4  7  5]
 [ 3  3  9]
 [ 3 17  6]
 [ 1  6  8]
 [ 3

* 将位置数据按照block，subaisle和picker的顺序进行排序

In [56]:
idex=np.lexsort([All_location[:,2],All_location[:,1],-1*All_location[:,0]])
a_sort=All_location[idex,:]

In [57]:
idex1=np.lexsort([picker_location[:,2],picker_location[:,1],-1*picker_location[:,0]])
a_sort1=picker_location[idex1,:]

* 首先计算每个点的位置坐标

In [58]:
arr_coordition=np.zeros((244,4))
arr_coordition[:,0]=a_sort[:,0]
arr_coordition[:,1]=a_sort[:,1]
arr_coordition[:,2]=a_sort[:,2]
for i in range(0,122):
    if a_sort[i,2]==0:
        arr_coordition[i,3]=0
    elif a_sort[i,2]==13:
        arr_coordition[i,3]=27
    else:
        arr_coordition[i,3]=(a_sort[i,2]-1)*2+2.5
for i in range(122,244):
    if a_sort[i,2]==0:
        arr_coordition[i,3]=0
    elif a_sort[i,2]==11:
        arr_coordition[i,3]=23
    else:
        arr_coordition[i,3]=(a_sort[i,2]-1)*2+2.5
print arr_coordition

[[  4.    1.    0.    0. ]
 [  4.    1.    5.   10.5]
 [  4.    1.   13.   27. ]
 [  4.    2.    0.    0. ]
 [  4.    2.    1.    2.5]
 [  4.    2.   11.   22.5]
 [  4.    2.   13.   27. ]
 [  4.    3.    0.    0. ]
 [  4.    3.   13.   27. ]
 [  4.    4.    0.    0. ]
 [  4.    4.   13.   27. ]
 [  4.    5.    0.    0. ]
 [  4.    5.   13.   27. ]
 [  4.    6.    0.    0. ]
 [  4.    6.    4.    8.5]
 [  4.    6.    8.   16.5]
 [  4.    6.   13.   27. ]
 [  4.    7.    0.    0. ]
 [  4.    7.    4.    8.5]
 [  4.    7.    5.   10.5]
 [  4.    7.   11.   22.5]
 [  4.    7.   13.   27. ]
 [  4.    8.    0.    0. ]
 [  4.    8.    4.    8.5]
 [  4.    8.   13.   27. ]
 [  4.    9.    0.    0. ]
 [  4.    9.    3.    6.5]
 [  4.    9.   13.   27. ]
 [  4.   10.    0.    0. ]
 [  4.   10.    5.   10.5]
 [  4.   10.   13.   27. ]
 [  4.   11.    0.    0. ]
 [  4.   11.   11.   22.5]
 [  4.   11.   13.   27. ]
 [  4.   12.    0.    0. ]
 [  4.   12.    5.   10.5]
 [  4.   12.   13.   27. ]
 

* 按照不同block将拣货点划分到数组中

In [59]:
arr1_coordition=arr_coordition[arr_coordition[:,0]==1]
arr2_coordition=arr_coordition[arr_coordition[:,0]==2]
arr3_coordition=arr_coordition[arr_coordition[:,0]==3]
arr4_coordition=arr_coordition[arr_coordition[:,0]==4]
arr11=a_sort1[a_sort1[:,0]==1]
arr21=a_sort1[a_sort1[:,0]==2]
arr31=a_sort1[a_sort1[:,0]==3]
arr41=a_sort1[a_sort1[:,0]==4]
print arr1_coordition,len(arr1_coordition)
print '----------------------------'
print arr2_coordition,len(arr2_coordition)
print '----------------------------'
print arr3_coordition,len(arr3_coordition)
print '----------------------------'
print arr4_coordition,len(arr4_coordition)

[[  1.    1.    0.    0. ]
 [  1.    1.    6.   12.5]
 [  1.    1.   11.   23. ]
 [  1.    2.    0.    0. ]
 [  1.    2.   11.   23. ]
 [  1.    3.    0.    0. ]
 [  1.    3.    2.    4.5]
 [  1.    3.    4.    8.5]
 [  1.    3.    6.   12.5]
 [  1.    3.    9.   18.5]
 [  1.    3.   11.   23. ]
 [  1.    4.    0.    0. ]
 [  1.    4.    2.    4.5]
 [  1.    4.   11.   23. ]
 [  1.    5.    0.    0. ]
 [  1.    5.   10.   20.5]
 [  1.    5.   11.   23. ]
 [  1.    6.    0.    0. ]
 [  1.    6.    7.   14.5]
 [  1.    6.    8.   16.5]
 [  1.    6.   11.   23. ]
 [  1.    7.    0.    0. ]
 [  1.    7.    1.    2.5]
 [  1.    7.   11.   23. ]
 [  1.    8.    0.    0. ]
 [  1.    8.    1.    2.5]
 [  1.    8.   11.   23. ]
 [  1.    9.    0.    0. ]
 [  1.    9.   11.   23. ]
 [  1.   10.    0.    0. ]
 [  1.   10.    6.   12.5]
 [  1.   10.    9.   18.5]
 [  1.   10.   11.   23. ]
 [  1.   11.    0.    0. ]
 [  1.   11.    6.   12.5]
 [  1.   11.   11.   23. ]
 [  1.   12.    0.    0. ]
 

* 接下来判断最远的需要拣货的block是block 4, 所以从block4开始优化

In [60]:
alen4=100
blen4=84
La_Route=[[1,1,0],
          [1,1,11],
          [2,1,0],
          [2,1,11],
          [3,1,0],
          [3,1,13],
          [4,1,0],
         [4,1,13]]
Lb_Route=[[1,1,0],
          [1,1,11],
          [2,1,0],
          [2,1,11],
          [3,1,0],
          [3,1,13],
          [4,1,0],
         [4,1,5],
         [4,1,0]]
Last_array=arr41[-1,1]   #判断最后一个需要拣货的走道
for i in range(2,Last_array):       
    arr4_sorted=arr4_coordition[arr4_coordition[:,1]==i]
    La1_Route=La_Route
    if len(arr4_sorted)==2:                       #当该巷道没有货的时候，就不用拣货，直接走到下一巷道
        alen4=alen4+3
        La_Route=np.vstack((La_Route,[4,i,13]))
        blen4=blen4+3
        Lb_Route=np.vstack((Lb_Route,[4,i,0]))
    else:                  
        Laa=alen4+3+2*(27- arr4_sorted[1,3])    #计算4个距离
        Lba=blen4+3+27
        Lab=alen4+3+27
        Lbb=blen4+3+2*arr4_sorted[-2,3]
        if Laa<Lba:                             #对于下一个点后端决策点来说，如果Laa<Lba说明从后端取货再返回后端距离比较短
            La_Route=np.vstack((La_Route,[4,i,13],[4,i,arr4_sorted[1,2]],[4,i,13]))
            alen4=Laa 
        else:                                   #否则是从前端穿过后端距离比较短  
            La_Route=np.vstack((Lb_Route,[4,i,0],[4,i,13]))
            alen4=Lba
        if Lbb<Lab:                             #对于下一个点前端决策点来说，如果Lbb<Lab说明从前端取货再返回前端距离比较短
            Lb_Route=np.vstack((Lb_Route,[4,i,0],[4,i,arr4_sorted[-2,2]],[4,i,0]))
            blen4=Lbb
        else:                                   #否则是从前端穿过后端距离比较短  
            Lb_Route=np.vstack((La1_Route,[4,i,13],[4,i,0]))
            blen4=Lab
Lab=alen4+3+27                                  #计算在最右拣货通道的距离，Lab是从后端穿越到前端，Lbb是从前端取货再返回前端
Lbb=blen4+3+2*arr4_coordition[-4,3]
if Lbb<Lab:                                     #说明从前端取货再返回前端的距离比较短
    blen4=Lbb
    Route4=np.vstack((Lb_Route,[4,arr4_coordition[-4,1],0],[4,arr4_coordition[-4,1],arr4_coordition[-4,2]],[4,arr4_coordition[-4,1],0]))
else:                                           #否则应该从后端穿越到前端
    Route4=np.vstack((La_Route,[4,arr4_coordition[-4,1],13],[4,arr4_coordition[-4,1],0]))
    blen4=Lab
print blen4, Route4

424.0 [[  1.   1.   0.]
 [  1.   1.  11.]
 [  2.   1.   0.]
 [  2.   1.  11.]
 [  3.   1.   0.]
 [  3.   1.  13.]
 [  4.   1.   0.]
 [  4.   1.   5.]
 [  4.   1.   0.]
 [  4.   2.   0.]
 [  4.   2.  13.]
 [  4.   3.  13.]
 [  4.   4.  13.]
 [  4.   5.  13.]
 [  4.   6.  13.]
 [  4.   6.   0.]
 [  4.   7.   0.]
 [  4.   7.  13.]
 [  4.   8.  13.]
 [  4.   8.   0.]
 [  4.   9.   0.]
 [  4.   9.   3.]
 [  4.   9.   0.]
 [  4.  10.   0.]
 [  4.  10.  13.]
 [  4.  11.  13.]
 [  4.  11.  11.]
 [  4.  11.  13.]
 [  4.  12.  13.]
 [  4.  12.   0.]
 [  4.  13.   0.]
 [  4.  13.  13.]
 [  4.  14.  13.]
 [  4.  14.   0.]
 [  4.  15.   0.]
 [  4.  16.   0.]
 [  4.  16.  13.]
 [  4.  17.  13.]
 [  4.  17.   0.]]


* 同样的方法对于block3进行优化

In [61]:
alen3=8
blen3=30
La_Route=[[3,17,13],
         [3,18,13],
         [3,18,12],
         [3,18,13]]
Lb_Route=[[3,17,13],
         [3,18,13],
         [3,18,0]]
Right_array=arr31[-1,1]   #判断最后一个需要拣货的走道
Left_array=arr31[2,1]     #
for i in range(Right_array-1,2,-1):       
    arr3_sorted=arr3_coordition[arr3_coordition[:,1]==i]
    La1_Route=La_Route
    if len(arr3_sorted)==2:                       #当该巷道没有货的时候，就不用拣货，直接走到下一巷道
        alen3=alen3+3
        La_Route=np.vstack((La_Route,[3,i,13]))
        blen3=blen3+3
        Lb_Route=np.vstack((Lb_Route,[3,i,0]))
    else:                  
        Laa=alen3+3+2*(27- arr3_sorted[1,3])    #计算4个距离
        Lba=blen3+3+27
        Lab=alen3+3+27
        Lbb=blen3+3+2*arr3_sorted[-2,3]
        if Laa<Lba:                             #对于下一个点后端决策点来说，有两种方法到达，一种是从后端取货再返回后端，
            La_Route=np.vstack((La_Route,[3,i,13],[3,i,arr3_sorted[1,2]],[3,i,13]))
            alen3=Laa 
        else:                                   #另一种是从前端穿过后端    
            La_Route=np.vstack((Lb_Route,[3,i,0],[3,i,13]))
            alen3=Lba
        if Lbb<Lab:
            Lb_Route=np.vstack((Lb_Route,[3,i,0],[3,i,arr3_sorted[-2,2]],[3,i,0]))
            blen3=Lbb
        else:
            Lb_Route=np.vstack((La1_Route,[3,i,13],[3,i,0]))
            blen3=Lab
Lab=alen3+3+27
Lbb=blen3+3+2*arr3_coordition[5,3]
if Lbb<Lab:
    blen3=Lbb
    Route3=np.vstack((Lb_Route,[3,arr3_coordition[5,1],0],[3,arr3_coordition[5,1],arr3_coordition[5,2]],[3,arr3_coordition[5,1],0]))
else:
    Route3=np.vstack((La_Route,[3,arr3_coordition[5,1],13],[3,arr3_coordition[5,1],0]))
    blen3=Lab
print blen3, Route3

336.0 [[  3.  17.  13.]
 [  3.  18.  13.]
 [  3.  18.  12.]
 [  3.  18.  13.]
 [  3.  17.  13.]
 [  3.  17.   0.]
 [  3.  16.   0.]
 [  3.  16.   1.]
 [  3.  16.   0.]
 [  3.  15.   0.]
 [  3.  15.   1.]
 [  3.  15.   0.]
 [  3.  14.   0.]
 [  3.  14.   6.]
 [  3.  14.   0.]
 [  3.  13.   0.]
 [  3.  13.   3.]
 [  3.  13.   0.]
 [  3.  12.   0.]
 [  3.  12.  13.]
 [  3.  11.  13.]
 [  3.  11.   0.]
 [  3.  10.   0.]
 [  3.   9.   0.]
 [  3.   9.   1.]
 [  3.   9.   0.]
 [  3.   8.   0.]
 [  3.   7.   0.]
 [  3.   7.  13.]
 [  3.   6.  13.]
 [  3.   6.   6.]
 [  3.   6.  13.]
 [  3.   5.  13.]
 [  3.   5.  11.]
 [  3.   5.  13.]
 [  3.   4.  13.]
 [  3.   4.   0.]
 [  3.   3.   0.]
 [  3.   3.  13.]
 [  3.   2.  13.]
 [  3.   2.   0.]]


* 同样的方法对于block2进行优化

In [62]:
alen2=44
blen2=26
La_Route=[[2,2,11],
         [2,3,11],
         [2,3,1],
         [2,3,11]]
Lb_Route=[[2,2,11],
         [2,3,11],
         [2,3,0]]
Right_array=arr21[-1,1]   #判断最后一个需要拣货的走道
for i in range(2,Right_array):       
    arr2_sorted=arr2_coordition[arr2_coordition[:,1]==i]
    La1_Route=La_Route
    if len(arr2_sorted)==2:                       #当该巷道没有货的时候，就不用拣货，直接走到下一巷道
        alen2=alen2+3
        La_Route=np.vstack((La_Route,[2,i,11]))
        blen2=blen2+3
        Lb_Route=np.vstack((Lb_Route,[2,i,0]))
    else:                  
        Laa=alen2+3+2*(23- arr2_sorted[1,3])    #计算4个距离
        Lba=blen2+3+23
        Lab=alen2+3+23
        Lbb=blen2+3+2*arr2_sorted[-2,3]
        if Laa<Lba:                             #对于下一个点后端决策点来说，有两种方法到达，一种是从后端取货再返回后端，
            La_Route=np.vstack((La_Route,[2,i,11],[2,i,arr2_sorted[1,2]],[2,i,11]))
            alen2=Laa 
        else:                                   #另一种是从前端穿过后端    
            La_Route=np.vstack((Lb_Route,[2,i,0],[2,i,11]))
            alen2=Lba
        if Lbb<Lab:
            Lb_Route=np.vstack((Lb_Route,[2,i,0],[2,i,arr2_sorted[-2,2]],[2,i,0]))
            blen2=Lbb
        else:
            Lb_Route=np.vstack((La1_Route,[2,i,11],[2,i,0]))
            blen2=Lab
Lab=alen2+3+23
Lbb=blen2+3+2*arr2_coordition[-4,3]
if Lbb<Lab:
    blen2=Lbb
    Route2=np.vstack((Lb_Route,[2,arr2_coordition[-4,1],0],[2,arr2_coordition[-4,1],arr2_coordition[-4,2]],[2,arr2_coordition[-4,1],0]))
else:
    Route2=np.vstack((La_Route,[2,arr2_coordition[-4,1],13],[2,arr2_coordition[-4,1],0]))
    blen2=Lab
print blen2, Route2

356.0 [[  2.   2.  11.]
 [  2.   3.  11.]
 [  2.   3.   0.]
 [  2.   2.   0.]
 [  2.   3.   0.]
 [  2.   3.  11.]
 [  2.   4.  11.]
 [  2.   4.   0.]
 [  2.   5.   0.]
 [  2.   5.  11.]
 [  2.   6.  11.]
 [  2.   6.   9.]
 [  2.   6.  11.]
 [  2.   7.  11.]
 [  2.   7.   0.]
 [  2.   8.   0.]
 [  2.   8.  11.]
 [  2.   9.  11.]
 [  2.   9.   0.]
 [  2.  10.   0.]
 [  2.  10.  11.]
 [  2.  11.  11.]
 [  2.  12.  11.]
 [  2.  12.   0.]
 [  2.  13.   0.]
 [  2.  13.  11.]
 [  2.  14.  11.]
 [  2.  14.  10.]
 [  2.  14.  11.]
 [  2.  15.  11.]
 [  2.  15.  10.]
 [  2.  15.  11.]
 [  2.  16.  11.]
 [  2.  16.   0.]
 [  2.  17.   0.]
 [  2.  17.   8.]
 [  2.  17.   0.]]


* 同样的方法对于block1进行优化

In [63]:
alen1=13
blen1=23
La_Route=[[2,17,13],
         [2,17,8],
         [2,17,13]]
Lb_Route=[[2,17,13],
         [2,17,0]]
Right_array=arr11[-1,1]   #判断最后一个需要拣货的走道
Left_array=arr11[1,1]
for i in range(Right_array-1,3,-1):       
    arr1_sorted=arr1_coordition[arr1_coordition[:,1]==i]
    La1_Route=La_Route
    if len(arr1_sorted)==2:                       #当该巷道没有货的时候，就不用拣货，直接走到下一巷道
        alen1=alen1+3
        La_Route=np.vstack((La_Route,[1,i,13]))
        blen1=blen1+3
        Lb_Route=np.vstack((Lb_Route,[1,i,0]))
    else:                  
        Laa=alen1+3+2*(23- arr1_sorted[1,3])    #计算4个距离
        Lba=blen1+3+23
        Lab=alen1+3+23
        Lbb=blen1+3+2*arr1_sorted[-2,3]
        if Laa<Lba:                             #对于下一个点后端决策点来说，有两种方法到达，一种是从后端取货再返回后端，
            La_Route=np.vstack((La_Route,[1,i,11],[1,i,arr1_sorted[1,2]],[1,i,11]))
            alen1=Laa 
        else:                                   #另一种是从前端穿过后端    
            La_Route=np.vstack((Lb_Route,[1,i,0],[1,i,11]))
            alen1=Lba
        if Lbb<Lab:
            Lb_Route=np.vstack((Lb_Route,[1,i,0],[1,i,arr1_sorted[-2,2]],[1,i,0]))
            blen1=Lbb
        else:
            Lb_Route=np.vstack((La1_Route,[1,i,11],[1,i,0]))
            blen1=Lab
Lab=alen1+3+23
Lbb=blen1+3+2*arr1_coordition[6,3]
if Lbb<Lab:
    blen1=Lbb
    Route1=np.vstack((Lb_Route,[1,arr1_coordition[6,1],0],[1,arr1_coordition[6,1],arr1_coordition[6,2]],[1,arr1_coordition[6,1],0]))
else:
    Route1=np.vstack((La_Route,[1,arr1_coordition[6,1],11],[1,arr1_coordition[6,1],0]))
    blen1=Lab
Route1=np.vstack((Route1,[1,2,0],[1,1,0]))
blen1=blen1+6
print blen1, Route1

234.0 [[  2.  17.  13.]
 [  2.  17.   8.]
 [  2.  17.  13.]
 [  1.  16.  13.]
 [  1.  15.  11.]
 [  1.  15.   5.]
 [  1.  15.  11.]
 [  1.  14.  11.]
 [  1.  14.   9.]
 [  1.  14.  11.]
 [  1.  13.  13.]
 [  1.  12.  11.]
 [  1.  12.   0.]
 [  1.  11.   0.]
 [  1.  11.  11.]
 [  1.  10.  11.]
 [  1.  10.   0.]
 [  1.   9.   0.]
 [  1.   8.   0.]
 [  1.   8.   1.]
 [  1.   8.   0.]
 [  1.   7.   0.]
 [  1.   7.   1.]
 [  1.   7.   0.]
 [  1.   6.   0.]
 [  1.   6.  11.]
 [  1.   5.  11.]
 [  1.   5.  10.]
 [  1.   5.  11.]
 [  1.   4.  11.]
 [  1.   4.   0.]
 [  1.   3.   0.]
 [  1.   3.   2.]
 [  1.   3.   0.]
 [  1.   2.   0.]
 [  1.   1.   0.]]


 * 最后将总距离相加，将各个block的路径连在一起得到总路径

In [64]:
Total_length=blen1+blen2+blen3+blen4
Route=np.vstack((Route4,Route3,Route2,Route1))
print Total_length,Route

1350.0 [[  1.   1.   0.]
 [  1.   1.  11.]
 [  2.   1.   0.]
 [  2.   1.  11.]
 [  3.   1.   0.]
 [  3.   1.  13.]
 [  4.   1.   0.]
 [  4.   1.   5.]
 [  4.   1.   0.]
 [  4.   2.   0.]
 [  4.   2.  13.]
 [  4.   3.  13.]
 [  4.   4.  13.]
 [  4.   5.  13.]
 [  4.   6.  13.]
 [  4.   6.   0.]
 [  4.   7.   0.]
 [  4.   7.  13.]
 [  4.   8.  13.]
 [  4.   8.   0.]
 [  4.   9.   0.]
 [  4.   9.   3.]
 [  4.   9.   0.]
 [  4.  10.   0.]
 [  4.  10.  13.]
 [  4.  11.  13.]
 [  4.  11.  11.]
 [  4.  11.  13.]
 [  4.  12.  13.]
 [  4.  12.   0.]
 [  4.  13.   0.]
 [  4.  13.  13.]
 [  4.  14.  13.]
 [  4.  14.   0.]
 [  4.  15.   0.]
 [  4.  16.   0.]
 [  4.  16.  13.]
 [  4.  17.  13.]
 [  4.  17.   0.]
 [  3.  17.  13.]
 [  3.  18.  13.]
 [  3.  18.  12.]
 [  3.  18.  13.]
 [  3.  17.  13.]
 [  3.  17.   0.]
 [  3.  16.   0.]
 [  3.  16.   1.]
 [  3.  16.   0.]
 [  3.  15.   0.]
 [  3.  15.   1.]
 [  3.  15.   0.]
 [  3.  14.   0.]
 [  3.  14.   6.]
 [  3.  14.   0.]
 [  3.  13.   0.]
 [ 

* 最后对计算利用combined heuristic算法进行仓库拣货路径规划的耗时

In [65]:
def test(n):
    """Stupid test function"""
    L = []
    for i in range(n):
        L.append(i)

if __name__ == '__main__':
    test_round = 1000
time_cost = timeit.timeit("test(10000)", setup="from __main__ import test", number = test_round)
print "test_case1: ", time_cost/test_round

test_case1:  0.00434466911226
