# Largest gap heuristic

* 引入本项目所需程序包

In [145]:
import numpy as np
import timeit

* 读取picker location数据

In [146]:
# loadtxt, 明确指定每列数据的类型
filename = './picker location.txt'
picker_location = np.loadtxt(filename,  #文件名
                        dtype=int)      #数据类型
print picker_location, picker_location.shape

[[ 3  7  4]
 [ 1  3  9]
 [ 3  7  3]
 [ 2  9  2]
 [ 3 14  6]
 [ 4 14 11]
 [ 1 14 10]
 [ 3 11  1]
 [ 2  6  9]
 [ 4  2  1]
 [ 4  7  4]
 [ 2 16  3]
 [ 4 17  9]
 [ 2  3  1]
 [ 3  2  9]
 [ 2 17  8]
 [ 3 15  1]
 [ 1 12  1]
 [ 3 12  8]
 [ 4  6  8]
 [ 3  3  5]
 [ 4 13  4]
 [ 1  3  2]
 [ 2 12  7]
 [ 1  4  2]
 [ 1 17  4]
 [ 2 13 10]
 [ 1  1  6]
 [ 2  1  3]
 [ 2  8  4]
 [ 1  3  6]
 [ 3  9  1]
 [ 4 16  2]
 [ 1  3  4]
 [ 3  5 11]
 [ 4 17 11]
 [ 1  6  7]
 [ 4 10  5]
 [ 2 14 10]
 [ 1 12  8]
 [ 4  6  4]
 [ 4  7 11]
 [ 2  7  2]
 [ 4 12  5]
 [ 3  6  6]
 [ 2 10  1]
 [ 2  3  5]
 [ 3  4  7]
 [ 3  1  3]
 [ 1  8  1]
 [ 4  9  3]
 [ 3 16  1]
 [ 1 10  6]
 [ 3 11  5]
 [ 4  8  4]
 [ 3  5 11]
 [ 4 11 11]
 [ 3 11  6]
 [ 1 12  3]
 [ 2  8  8]
 [ 2  9  3]
 [ 2 13  4]
 [ 3 18 12]
 [ 2 10  8]
 [ 1 14  9]
 [ 2  5  3]
 [ 1 14 10]
 [ 1 12  6]
 [ 2  8  6]
 [ 2  3  7]
 [ 4 13  5]
 [ 1 17  6]
 [ 4  2 11]
 [ 3  7  8]
 [ 1 10  9]
 [ 1  7  1]
 [ 2  4  8]
 [ 3 11  9]
 [ 3  7  5]
 [ 4  7  5]
 [ 3  3  9]
 [ 3 17  6]
 [ 1  6  8]
 [ 3

* 读取包含前侧和后侧决策点的所有位置数据

In [147]:
# loadtxt, 明确指定每列数据的类型
filename = './AllLocation.csv'
All_location = np.loadtxt(filename,         #文件名
                          delimiter=',',    #分割符
                          dtype=int         #数据类型
                         )  
print All_location, All_location.shape

[[ 3  7  4]
 [ 1  3  9]
 [ 3  7  3]
 [ 2  9  2]
 [ 3 14  6]
 [ 4 14 11]
 [ 1 14 10]
 [ 3 11  1]
 [ 2  6  9]
 [ 4  2  1]
 [ 4  7  4]
 [ 2 16  3]
 [ 4 17  9]
 [ 2  3  1]
 [ 3  2  9]
 [ 2 17  8]
 [ 3 15  1]
 [ 1 12  1]
 [ 3 12  8]
 [ 4  6  8]
 [ 3  3  5]
 [ 4 13  4]
 [ 1  3  2]
 [ 2 12  7]
 [ 1  4  2]
 [ 1 17  4]
 [ 2 13 10]
 [ 1  1  6]
 [ 2  1  3]
 [ 2  8  4]
 [ 1  3  6]
 [ 3  9  1]
 [ 4 16  2]
 [ 1  3  4]
 [ 3  5 11]
 [ 4 17 11]
 [ 1  6  7]
 [ 4 10  5]
 [ 2 14 10]
 [ 1 12  8]
 [ 4  6  4]
 [ 4  7 11]
 [ 2  7  2]
 [ 4 12  5]
 [ 3  6  6]
 [ 2 10  1]
 [ 2  3  5]
 [ 3  4  7]
 [ 3  1  3]
 [ 1  8  1]
 [ 4  9  3]
 [ 3 16  1]
 [ 1 10  6]
 [ 3 11  5]
 [ 4  8  4]
 [ 3  5 11]
 [ 4 11 11]
 [ 3 11  6]
 [ 1 12  3]
 [ 2  8  8]
 [ 2  9  3]
 [ 2 13  4]
 [ 3 18 12]
 [ 2 10  8]
 [ 1 14  9]
 [ 2  5  3]
 [ 1 14 10]
 [ 1 12  6]
 [ 2  8  6]
 [ 2  3  7]
 [ 4 13  5]
 [ 1 17  6]
 [ 4  2 11]
 [ 3  7  8]
 [ 1 10  9]
 [ 1  7  1]
 [ 2  4  8]
 [ 3 11  9]
 [ 3  7  5]
 [ 4  7  5]
 [ 3  3  9]
 [ 3 17  6]
 [ 1  6  8]
 [ 3

* 将位置数据按照block，subaisle和picker的顺序进行排序

In [148]:
idex=np.lexsort([All_location[:,2],All_location[:,1],-1*All_location[:,0]])
a_sort=All_location[idex,:]

In [149]:
idex1=np.lexsort([picker_location[:,2],picker_location[:,1],-1*picker_location[:,0]])
a_sort1=picker_location[idex1,:]

* 首先计算每个点的位置坐标

In [150]:
arr_coordition=np.zeros((244,4))
arr_coordition[:,0]=a_sort[:,0]
arr_coordition[:,1]=a_sort[:,1]
arr_coordition[:,2]=a_sort[:,2]
for i in range(0,122):
    if a_sort[i,2]==0:
        arr_coordition[i,3]=0
    elif a_sort[i,2]==13:
        arr_coordition[i,3]=27
    else:
        arr_coordition[i,3]=(a_sort[i,2]-1)*2+2.5
for i in range(122,244):
    if a_sort[i,2]==0:
        arr_coordition[i,3]=0
    elif a_sort[i,2]==11:
        arr_coordition[i,3]=23
    else:
        arr_coordition[i,3]=(a_sort[i,2]-1)*2+2.5
print arr_coordition

[[  4.    1.    0.    0. ]
 [  4.    1.    5.   10.5]
 [  4.    1.   13.   27. ]
 [  4.    2.    0.    0. ]
 [  4.    2.    1.    2.5]
 [  4.    2.   11.   22.5]
 [  4.    2.   13.   27. ]
 [  4.    3.    0.    0. ]
 [  4.    3.   13.   27. ]
 [  4.    4.    0.    0. ]
 [  4.    4.   13.   27. ]
 [  4.    5.    0.    0. ]
 [  4.    5.   13.   27. ]
 [  4.    6.    0.    0. ]
 [  4.    6.    4.    8.5]
 [  4.    6.    8.   16.5]
 [  4.    6.   13.   27. ]
 [  4.    7.    0.    0. ]
 [  4.    7.    4.    8.5]
 [  4.    7.    5.   10.5]
 [  4.    7.   11.   22.5]
 [  4.    7.   13.   27. ]
 [  4.    8.    0.    0. ]
 [  4.    8.    4.    8.5]
 [  4.    8.   13.   27. ]
 [  4.    9.    0.    0. ]
 [  4.    9.    3.    6.5]
 [  4.    9.   13.   27. ]
 [  4.   10.    0.    0. ]
 [  4.   10.    5.   10.5]
 [  4.   10.   13.   27. ]
 [  4.   11.    0.    0. ]
 [  4.   11.   11.   22.5]
 [  4.   11.   13.   27. ]
 [  4.   12.    0.    0. ]
 [  4.   12.    5.   10.5]
 [  4.   12.   13.   27. ]
 

* 然后计算相邻拣货点之间，以及前后决策点与拣货点之间的距离

In [151]:
arr_distance=np.zeros((244,4))
arr_distance[:,0]=a_sort[:,0]
arr_distance[:,1]=a_sort[:,1]
arr_distance[:,2]=a_sort[:,2]
for i in range(1,244):
    arr_distance[i,3]=arr_coordition[i,3]-arr_coordition[i-1,3]
print arr_distance

[[  4.    1.    0.    0. ]
 [  4.    1.    5.   10.5]
 [  4.    1.   13.   16.5]
 [  4.    2.    0.  -27. ]
 [  4.    2.    1.    2.5]
 [  4.    2.   11.   20. ]
 [  4.    2.   13.    4.5]
 [  4.    3.    0.  -27. ]
 [  4.    3.   13.   27. ]
 [  4.    4.    0.  -27. ]
 [  4.    4.   13.   27. ]
 [  4.    5.    0.  -27. ]
 [  4.    5.   13.   27. ]
 [  4.    6.    0.  -27. ]
 [  4.    6.    4.    8.5]
 [  4.    6.    8.    8. ]
 [  4.    6.   13.   10.5]
 [  4.    7.    0.  -27. ]
 [  4.    7.    4.    8.5]
 [  4.    7.    5.    2. ]
 [  4.    7.   11.   12. ]
 [  4.    7.   13.    4.5]
 [  4.    8.    0.  -27. ]
 [  4.    8.    4.    8.5]
 [  4.    8.   13.   18.5]
 [  4.    9.    0.  -27. ]
 [  4.    9.    3.    6.5]
 [  4.    9.   13.   20.5]
 [  4.   10.    0.  -27. ]
 [  4.   10.    5.   10.5]
 [  4.   10.   13.   16.5]
 [  4.   11.    0.  -27. ]
 [  4.   11.   11.   22.5]
 [  4.   11.   13.    4.5]
 [  4.   12.    0.  -27. ]
 [  4.   12.    5.   10.5]
 [  4.   12.   13.   16.5]
 

* 按照不同block将拣货点划分到数组中

In [152]:
arr1_distance=arr_distance[arr_distance[:,0]==1]
arr2_distance=arr_distance[arr_distance[:,0]==2]
arr3_distance=arr_distance[arr_distance[:,0]==3]
arr4_distance=arr_distance[arr_distance[:,0]==4]
arr11=a_sort1[a_sort1[:,0]==1]
arr21=a_sort1[a_sort1[:,0]==2]
arr31=a_sort1[a_sort1[:,0]==3]
arr41=a_sort1[a_sort1[:,0]==4]
print arr1_distance,len(arr1_distance)
print '----------------------------'
print arr2_distance,len(arr2_distance)
print '----------------------------'
print arr3_distance,len(arr3_distance)
print '----------------------------'
print arr4_distance,len(arr4_distance)

[[  1.    1.    0.  -23. ]
 [  1.    1.    6.   12.5]
 [  1.    1.   11.   10.5]
 [  1.    2.    0.  -23. ]
 [  1.    2.   11.   23. ]
 [  1.    3.    0.  -23. ]
 [  1.    3.    2.    4.5]
 [  1.    3.    4.    4. ]
 [  1.    3.    6.    4. ]
 [  1.    3.    9.    6. ]
 [  1.    3.   11.    4.5]
 [  1.    4.    0.  -23. ]
 [  1.    4.    2.    4.5]
 [  1.    4.   11.   18.5]
 [  1.    5.    0.  -23. ]
 [  1.    5.   10.   20.5]
 [  1.    5.   11.    2.5]
 [  1.    6.    0.  -23. ]
 [  1.    6.    7.   14.5]
 [  1.    6.    8.    2. ]
 [  1.    6.   11.    6.5]
 [  1.    7.    0.  -23. ]
 [  1.    7.    1.    2.5]
 [  1.    7.   11.   20.5]
 [  1.    8.    0.  -23. ]
 [  1.    8.    1.    2.5]
 [  1.    8.   11.   20.5]
 [  1.    9.    0.  -23. ]
 [  1.    9.   11.   23. ]
 [  1.   10.    0.  -23. ]
 [  1.   10.    6.   12.5]
 [  1.   10.    9.    6. ]
 [  1.   10.   11.    4.5]
 [  1.   11.    0.  -23. ]
 [  1.   11.    6.   12.5]
 [  1.   11.   11.   10.5]
 [  1.   12.    0.  -23. ]
 

* 接下来判断最远的需要拣货的block是block 4, 所以从block4开始优化

In [153]:
len4=103
Forward_Route=[[1,1,0], #存储从block后侧的拣货路径
       [1,1,11],
       [2,1,0],
       [2,1,11],
      [3,1,0],
      [3,1,13],
      [4,1,0],
      [4,1,13],
      [4,2,13]]
Re_Route=np.zeros((1,3))  #存储从block前侧的拣货路径
Last_array=arr41[-1,1]   #判断最后一个需要拣货的走道
for i in range(2,Last_array):       
    arr4_sorted=arr4_distance[arr4_distance[:,1]==i]
    mix_distance4=np.max(arr4_sorted[:,3])     #选取每一个asile所有间隔中最大的间隔
    re=np.where(arr4_sorted==mix_distance4)    #选取最大间隔所在的位置
    mix_picker4=re[0][0]
    if mix_distance4==27:        #如果最大值为27，说明该通道内没有货物需要拣
        len4=len4+6              
        Forward_Route=np.vstack((Forward_Route,[4,i+1,13]))
        Re_Route=np.vstack((Re_Route,[4,i+1,0]))
    elif (arr4_sorted[mix_picker4,2]==13)&(mix_distance4<27): #如果最大值在后端决策点和相邻的拣货点之间，那么就从对面前端取货
        len4=len4+3+3+(27-mix_distance4)*2
        Forward_Route=np.vstack((Forward_Route,[4,i+1,13]))
        Re_Route=np.vstack((Re_Route,[4,i,arr4_sorted[mix_picker4-1,2]],[4,i,0],[4,i+1,0]))
    elif (arr4_sorted[mix_picker4-1,2]==0):       #如果最大间隔在前端决策点和相邻的拣货点之间，那么就从后端拣货
        len4=len4+3+3+2*(27-mix_distance4)
        Forward_Route=np.vstack((Forward_Route,[4,i,arr4_sorted[mix_picker4,2]],[4,i,13],[4,i+1,13]))
        Re_Route=np.vstack((Re_Route,[4,i+1,0]))
    else:
        len4=len4+3+3+2*(27-mix_distance4)        #如果最大间隔在相邻两个拣货点之间，那么从两端入口分别拣货
        Forward_Route=np.vstack((Forward_Route,[4,i,arr4_sorted[mix_picker4,2]],[4,i,13],[4,i+1,13]))
        Re_Route=np.vstack((Re_Route,[4,i,arr4_sorted[mix_picker4-1,2]],[4,i,0],[4,i+1,0]))
len4=len4+24
Re_Route[0,:]=[4,2,0]
idex4=np.lexsort([-1*Re_Route[:,1]])
Re_Route=Re_Route[idex4,:]
Route4=np.vstack((Forward_Route,Re_Route))      #后侧拣货路径与前侧拣货路径合起来就是block的最优拣货路径
print len4, Route4

414.0 [[  1.   1.   0.]
 [  1.   1.  11.]
 [  2.   1.   0.]
 [  2.   1.  11.]
 [  3.   1.   0.]
 [  3.   1.  13.]
 [  4.   1.   0.]
 [  4.   1.  13.]
 [  4.   2.  13.]
 [  4.   2.  11.]
 [  4.   2.  13.]
 [  4.   3.  13.]
 [  4.   4.  13.]
 [  4.   5.  13.]
 [  4.   6.  13.]
 [  4.   7.  13.]
 [  4.   7.  11.]
 [  4.   7.  13.]
 [  4.   8.  13.]
 [  4.   9.  13.]
 [  4.  10.  13.]
 [  4.  11.  13.]
 [  4.  11.  11.]
 [  4.  11.  13.]
 [  4.  12.  13.]
 [  4.  13.  13.]
 [  4.  14.  13.]
 [  4.  14.  11.]
 [  4.  14.  13.]
 [  4.  15.  13.]
 [  4.  16.  13.]
 [  4.  17.  13.]
 [  4.  17.   0.]
 [  4.  16.   0.]
 [  4.  16.   2.]
 [  4.  16.   0.]
 [  4.  15.   0.]
 [  4.  14.   0.]
 [  4.  13.   0.]
 [  4.  13.   5.]
 [  4.  13.   0.]
 [  4.  12.   0.]
 [  4.  12.   5.]
 [  4.  12.   0.]
 [  4.  11.   0.]
 [  4.  10.   0.]
 [  4.  10.   5.]
 [  4.  10.   0.]
 [  4.   9.   0.]
 [  4.   9.   3.]
 [  4.   9.   0.]
 [  4.   8.   0.]
 [  4.   8.   4.]
 [  4.   8.   0.]
 [  4.   7.   0.]
 [  

* 同样的方法对于block3进行优化

In [154]:
len3=0
Forward_Route=np.zeros((1,3))
Re_Route=np.zeros((1,3))
Last_array=arr31[-1,1]   #判断最后一个需要拣货的走道
for i in range(2,Last_array):       
    arr3_sorted=arr3_distance[arr3_distance[:,1]==i]
    mix_distance3=np.max(arr3_sorted[:,3])
    re=np.where(arr3_sorted==mix_distance3)    #选取最大间隔所在的位置
    mix_picker3=re[0][0]
    if mix_distance3==27:        #如果最大值为27，说明该通道内没有货物需要拣
        len3=len3+6              
        Forward_Route=np.vstack((Forward_Route,[3,i+1,13]))
        Re_Route=np.vstack((Re_Route,[3,i+1,0]))
    elif (arr3_sorted[mix_picker3,2]==13)&(mix_distance3<27):      #如果最大值在后端决策点和相邻的拣货点之间，那么就从对面取货
        len3=len3+3+3+(27-mix_distance3)*2
        Forward_Route=np.vstack((Forward_Route,[3,i+1,13]))
        Re_Route=np.vstack((Re_Route,[3,i,arr3_sorted[mix_picker3-1,2]],[3,i,0],[3,i+1,0]))
    elif arr3_sorted[mix_picker3-1,2]==0:
        len3=len3+3+3+2*(27-mix_distance3)
        Forward_Route=np.vstack((Forward_Route,[3,i,arr3_sorted[mix_picker3,2]],[3,i,13],[3,i+1,13]))
        Re_Route=np.vstack((Re_Route,[3,i+1,0]))
    else:
        len3=len3+3+3+2*(27-mix_distance3)
        Forward_Route=np.vstack((Forward_Route,[3,i,arr3_sorted[mix_picker3,2]],[3,i,13],[3,i+1,13]))
        Re_Route=np.vstack((Re_Route,[3,i,arr3_sorted[mix_picker3-1,2]],[3,i,0],[3,i+1,0]))
len3=len3+27
idex3=np.lexsort([-1*Re_Route[:,1]])
Re_Route=Re_Route[idex3,:]
Forward_Route[0,:]=[3,2,13]
Re_Route[-1,:]=[3,2,0]
Route3=np.vstack((Forward_Route,Re_Route))
print len3, Route3

425.0 [[  3.   2.  13.]
 [  3.   2.   9.]
 [  3.   2.  13.]
 [  3.   3.  13.]
 [  3.   4.  13.]
 [  3.   4.   7.]
 [  3.   4.  13.]
 [  3.   5.  13.]
 [  3.   5.  11.]
 [  3.   5.  13.]
 [  3.   6.  13.]
 [  3.   7.  13.]
 [  3.   7.   3.]
 [  3.   7.  13.]
 [  3.   8.  13.]
 [  3.   9.  13.]
 [  3.  10.  13.]
 [  3.  11.  13.]
 [  3.  12.  13.]
 [  3.  13.  13.]
 [  3.  14.  13.]
 [  3.  15.  13.]
 [  3.  16.  13.]
 [  3.  17.  13.]
 [  3.  18.  13.]
 [  3.  18.   0.]
 [  3.  17.   0.]
 [  3.  17.   6.]
 [  3.  17.   0.]
 [  3.  16.   0.]
 [  3.  16.   1.]
 [  3.  16.   0.]
 [  3.  15.   0.]
 [  3.  15.   1.]
 [  3.  15.   0.]
 [  3.  14.   0.]
 [  3.  14.   6.]
 [  3.  14.   0.]
 [  3.  13.   0.]
 [  3.  13.   3.]
 [  3.  13.   0.]
 [  3.  12.   0.]
 [  3.  12.   8.]
 [  3.  12.   0.]
 [  3.  11.   0.]
 [  3.  11.   9.]
 [  3.  11.   0.]
 [  3.  10.   0.]
 [  3.   9.   0.]
 [  3.   9.   1.]
 [  3.   9.   0.]
 [  3.   8.   0.]
 [  3.   7.   0.]
 [  3.   6.   0.]
 [  3.   6.   6.]
 [  

* 同样的方法对于block3进行优化

In [155]:
len2=0
Forward_Route=np.zeros((1,3))
Re_Route=np.zeros((1,3))
Last_array=arr21[-1,1]   #判断最后一个需要拣货的走道
for i in range(2,Last_array):       
    arr2_sorted=arr2_distance[arr2_distance[:,1]==i]
    mix_distance2=np.max(arr2_sorted[:,3])
    re=np.where(arr2_sorted==mix_distance2)    #选取最大间隔所在的位置
    mix_picker2=re[0][0]
    if mix_distance2==23:        #如果最大值为27，说明该通道内没有货物需要拣
        len2=len2+6              
        Forward_Route=np.vstack((Forward_Route,[2,i+1,11]))
        Re_Route=np.vstack((Re_Route,[2,i+1,0]))
    elif (arr2_sorted[mix_picker2,2]==11)&(mix_distance2<23):      #如果最大值在后端决策点和相邻的拣货点之间，那么就从对面取货
        len2=len2+3+3+(23-mix_distance2)*2
        Forward_Route=np.vstack((Forward_Route,[2,i+1,11]))
        Re_Route=np.vstack((Re_Route,[2,i,arr2_sorted[mix_picker2-1,2]],[2,i,0],[2,i+1,0]))
    elif arr2_sorted[mix_picker2-1,2]==0:
        len2=len2+3+3+2*(23-mix_distance2)
        Forward_Route=np.vstack((Forward_Route,[2,i,arr2_sorted[mix_picker2,2]],[2,i,11],[2,i+1,11]))
        Re_Route=np.vstack((Re_Route,[2,i+1,0]))
    else:
        len2=len2+3+3+2*(23-mix_distance2)
        Forward_Route=np.vstack((Forward_Route,[2,i,arr2_sorted[mix_picker2,2]],[2,i,11],[2,i+1,11]))
        Re_Route=np.vstack((Re_Route,[2,i,arr2_sorted[mix_picker2-1,2]],[2,i,0],[2,i+1,0]))
len2=len2+23
idex2=np.lexsort([-1*Re_Route[:,1]])
Re_Route=Re_Route[idex2,:]
Forward_Route[0,:]=[2,2,11]
Re_Route[-1,:]=[2,2,0]
Route2=np.vstack((Forward_Route,Re_Route))
print len2, Route2

308.0 [[  2.   2.  11.]
 [  2.   3.  11.]
 [  2.   4.  11.]
 [  2.   4.   8.]
 [  2.   4.  11.]
 [  2.   5.  11.]
 [  2.   6.  11.]
 [  2.   6.   9.]
 [  2.   6.  11.]
 [  2.   7.  11.]
 [  2.   8.  11.]
 [  2.   8.   4.]
 [  2.   8.  11.]
 [  2.   9.  11.]
 [  2.  10.  11.]
 [  2.  10.   8.]
 [  2.  10.  11.]
 [  2.  11.  11.]
 [  2.  12.  11.]
 [  2.  12.   7.]
 [  2.  12.  11.]
 [  2.  13.  11.]
 [  2.  13.  10.]
 [  2.  13.  11.]
 [  2.  14.  11.]
 [  2.  14.  10.]
 [  2.  14.  11.]
 [  2.  15.  11.]
 [  2.  15.  10.]
 [  2.  15.  11.]
 [  2.  16.  11.]
 [  2.  17.  11.]
 [  2.  17.   0.]
 [  2.  16.   0.]
 [  2.  16.   3.]
 [  2.  16.   0.]
 [  2.  15.   0.]
 [  2.  14.   0.]
 [  2.  13.   0.]
 [  2.  13.   4.]
 [  2.  13.   0.]
 [  2.  12.   0.]
 [  2.  11.   0.]
 [  2.  10.   0.]
 [  2.  10.   1.]
 [  2.  10.   0.]
 [  2.   9.   0.]
 [  2.   9.   3.]
 [  2.   9.   0.]
 [  2.   8.   0.]
 [  2.   7.   0.]
 [  2.   7.   2.]
 [  2.   7.   0.]
 [  2.   6.   0.]
 [  2.   5.   0.]
 [  

* 同样的方法对于block1进行优化

In [156]:
len1=0
Forward_Route=np.zeros((1,3))
Re_Route=np.zeros((1,3))
Last_array=arr11[-1,1]   #判断最后一个需要拣货的走道
for i in range(2,Last_array):       
    arr1_sorted=arr1_distance[arr1_distance[:,1]==i]
    mix_distance1=np.max(arr1_sorted[:,3])
    re=np.where(arr1_sorted==mix_distance1)    #选取最大间隔所在的位置
    mix_picker1=re[0][0]
    if mix_distance1==23:        #如果最大值为27，说明该通道内没有货物需要拣
        len1=len1+6              
        Forward_Route=np.vstack((Forward_Route,[1,i+1,11]))
        Re_Route=np.vstack((Re_Route,[1,i+1,0]))
    elif (arr1_sorted[mix_picker1,2]==11)&(mix_distance1<23):      #如果最大值在后端决策点和相邻的拣货点之间，那么就从对面取货
        len1=len1+3+3+(23-mix_distance1)*2
        Forward_Route=np.vstack((Forward_Route,[1,i+1,11]))
        Re_Route=np.vstack((Re_Route,[1,i,arr1_sorted[mix_picker1-1,2]],[1,i,0],[1,i+1,0]))
    elif arr1_sorted[mix_picker1-1,2]==0:
        len1=len1+3+3+2*(23-mix_distance1)
        Forward_Route=np.vstack((Forward_Route,[1,i,arr1_sorted[mix_picker1,2]],[1,i,11],[1,i+1,11]))
        Re_Route=np.vstack((Re_Route,[1,i+1,0]))
    else:
        len1=len1+3+3+2*(23-mix_distance1)
        Forward_Route=np.vstack((Forward_Route,[1,i,arr1_sorted[mix_picker1,2]],[1,i,11],[1,i+1,11]))
        Re_Route=np.vstack((Re_Route,[1,i,arr1_sorted[mix_picker1-1,2]],[1,i,0],[1,i+1,0]))
len1=len1+26
idex1=np.lexsort([-1*Re_Route[:,1]])
Re_Route=Re_Route[idex1,:]
Forward_Route[0,:]=[1,2,11]
Re_Route[-1,:]=[1,2,0]
Re_Route=np.vstack((Re_Route,[1,1,0]))
Route1=np.vstack((Forward_Route,Re_Route))
print len1, Route1  

296.0 [[  1.   2.  11.]
 [  1.   3.  11.]
 [  1.   3.   6.]
 [  1.   3.  11.]
 [  1.   4.  11.]
 [  1.   5.  11.]
 [  1.   5.  10.]
 [  1.   5.  11.]
 [  1.   6.  11.]
 [  1.   6.   7.]
 [  1.   6.  11.]
 [  1.   7.  11.]
 [  1.   8.  11.]
 [  1.   9.  11.]
 [  1.  10.  11.]
 [  1.  10.   6.]
 [  1.  10.  11.]
 [  1.  11.  11.]
 [  1.  11.   6.]
 [  1.  11.  11.]
 [  1.  12.  11.]
 [  1.  13.  11.]
 [  1.  14.  11.]
 [  1.  14.   9.]
 [  1.  14.  11.]
 [  1.  15.  11.]
 [  1.  16.  11.]
 [  1.  17.  11.]
 [  1.  17.   0.]
 [  1.  16.   0.]
 [  1.  15.   0.]
 [  1.  15.   5.]
 [  1.  15.   0.]
 [  1.  14.   0.]
 [  1.  13.   0.]
 [  1.  12.   0.]
 [  1.  12.   8.]
 [  1.  12.   0.]
 [  1.  11.   0.]
 [  1.  10.   0.]
 [  1.   9.   0.]
 [  1.   8.   0.]
 [  1.   8.   1.]
 [  1.   8.   0.]
 [  1.   7.   0.]
 [  1.   7.   1.]
 [  1.   7.   0.]
 [  1.   6.   0.]
 [  1.   5.   0.]
 [  1.   4.   0.]
 [  1.   4.   2.]
 [  1.   4.   0.]
 [  1.   3.   0.]
 [  1.   3.   4.]
 [  1.   3.   0.]
 [  

* 最后将总距离相加，将各个block的路径连在一起得到总路径

In [157]:
Total_length=len1+len2+len3+len4
Route=np.vstack((Route4,Route3,Route2,Route1))
print Total_length,Route

1443.0 [[  1.   1.   0.]
 [  1.   1.  11.]
 [  2.   1.   0.]
 [  2.   1.  11.]
 [  3.   1.   0.]
 [  3.   1.  13.]
 [  4.   1.   0.]
 [  4.   1.  13.]
 [  4.   2.  13.]
 [  4.   2.  11.]
 [  4.   2.  13.]
 [  4.   3.  13.]
 [  4.   4.  13.]
 [  4.   5.  13.]
 [  4.   6.  13.]
 [  4.   7.  13.]
 [  4.   7.  11.]
 [  4.   7.  13.]
 [  4.   8.  13.]
 [  4.   9.  13.]
 [  4.  10.  13.]
 [  4.  11.  13.]
 [  4.  11.  11.]
 [  4.  11.  13.]
 [  4.  12.  13.]
 [  4.  13.  13.]
 [  4.  14.  13.]
 [  4.  14.  11.]
 [  4.  14.  13.]
 [  4.  15.  13.]
 [  4.  16.  13.]
 [  4.  17.  13.]
 [  4.  17.   0.]
 [  4.  16.   0.]
 [  4.  16.   2.]
 [  4.  16.   0.]
 [  4.  15.   0.]
 [  4.  14.   0.]
 [  4.  13.   0.]
 [  4.  13.   5.]
 [  4.  13.   0.]
 [  4.  12.   0.]
 [  4.  12.   5.]
 [  4.  12.   0.]
 [  4.  11.   0.]
 [  4.  10.   0.]
 [  4.  10.   5.]
 [  4.  10.   0.]
 [  4.   9.   0.]
 [  4.   9.   3.]
 [  4.   9.   0.]
 [  4.   8.   0.]
 [  4.   8.   4.]
 [  4.   8.   0.]
 [  4.   7.   0.]
 [ 

* 最后对计算利用large-gap heuristic算法进行仓库拣货路径规划的耗时

In [158]:
def test(n):
    """Stupid test function"""
    L = []
    for i in range(n):
        L.append(i)

if __name__ == '__main__':
    test_round = 1000
time_cost = timeit.timeit("test(10000)", setup="from __main__ import test", number = test_round)
print "test_case1: ", time_cost/test_round

test_case1:  0.00346621698893
