# S-shape heuristic

* 引入本项目所需程序包

In [31]:
import numpy as np
import timeit

* 读取picker location数据

In [3]:
# loadtxt, 明确指定每列数据的类型
filename = './picker location.txt'
picker_location = np.loadtxt(filename,  #文件名
                        dtype=int)      #数据类型
print picker_location, picker_location.shape

[[ 3  7  4]
 [ 1  3  9]
 [ 3  7  3]
 [ 2  9  2]
 [ 3 14  6]
 [ 4 14 11]
 [ 1 14 10]
 [ 3 11  1]
 [ 2  6  9]
 [ 4  2  1]
 [ 4  7  4]
 [ 2 16  3]
 [ 4 17  9]
 [ 2  3  1]
 [ 3  2  9]
 [ 2 17  8]
 [ 3 15  1]
 [ 1 12  1]
 [ 3 12  8]
 [ 4  6  8]
 [ 3  3  5]
 [ 4 13  4]
 [ 1  3  2]
 [ 2 12  7]
 [ 1  4  2]
 [ 1 17  4]
 [ 2 13 10]
 [ 1  1  6]
 [ 2  1  3]
 [ 2  8  4]
 [ 1  3  6]
 [ 3  9  1]
 [ 4 16  2]
 [ 1  3  4]
 [ 3  5 11]
 [ 4 17 11]
 [ 1  6  7]
 [ 4 10  5]
 [ 2 14 10]
 [ 1 12  8]
 [ 4  6  4]
 [ 4  7 11]
 [ 2  7  2]
 [ 4 12  5]
 [ 3  6  6]
 [ 2 10  1]
 [ 2  3  5]
 [ 3  4  7]
 [ 3  1  3]
 [ 1  8  1]
 [ 4  9  3]
 [ 3 16  1]
 [ 1 10  6]
 [ 3 11  5]
 [ 4  8  4]
 [ 3  5 11]
 [ 4 11 11]
 [ 3 11  6]
 [ 1 12  3]
 [ 2  8  8]
 [ 2  9  3]
 [ 2 13  4]
 [ 3 18 12]
 [ 2 10  8]
 [ 1 14  9]
 [ 2  5  3]
 [ 1 14 10]
 [ 1 12  6]
 [ 2  8  6]
 [ 2  3  7]
 [ 4 13  5]
 [ 1 17  6]
 [ 4  2 11]
 [ 3  7  8]
 [ 1 10  9]
 [ 1  7  1]
 [ 2  4  8]
 [ 3 11  9]
 [ 3  7  5]
 [ 4  7  5]
 [ 3  3  9]
 [ 3 17  6]
 [ 1  6  8]
 [ 3

* 读取包含前侧和后侧决策点的所有位置数据

In [4]:
# loadtxt, 明确指定每列数据的类型
filename = './AllLocation.csv'
All_location = np.loadtxt(filename,         #文件名
                          delimiter=',',    #分割符
                          dtype=int         #数据类型
                         )  
print All_location, All_location.shape

[[ 3  7  4]
 [ 1  3  9]
 [ 3  7  3]
 [ 2  9  2]
 [ 3 14  6]
 [ 4 14 11]
 [ 1 14 10]
 [ 3 11  1]
 [ 2  6  9]
 [ 4  2  1]
 [ 4  7  4]
 [ 2 16  3]
 [ 4 17  9]
 [ 2  3  1]
 [ 3  2  9]
 [ 2 17  8]
 [ 3 15  1]
 [ 1 12  1]
 [ 3 12  8]
 [ 4  6  8]
 [ 3  3  5]
 [ 4 13  4]
 [ 1  3  2]
 [ 2 12  7]
 [ 1  4  2]
 [ 1 17  4]
 [ 2 13 10]
 [ 1  1  6]
 [ 2  1  3]
 [ 2  8  4]
 [ 1  3  6]
 [ 3  9  1]
 [ 4 16  2]
 [ 1  3  4]
 [ 3  5 11]
 [ 4 17 11]
 [ 1  6  7]
 [ 4 10  5]
 [ 2 14 10]
 [ 1 12  8]
 [ 4  6  4]
 [ 4  7 11]
 [ 2  7  2]
 [ 4 12  5]
 [ 3  6  6]
 [ 2 10  1]
 [ 2  3  5]
 [ 3  4  7]
 [ 3  1  3]
 [ 1  8  1]
 [ 4  9  3]
 [ 3 16  1]
 [ 1 10  6]
 [ 3 11  5]
 [ 4  8  4]
 [ 3  5 11]
 [ 4 11 11]
 [ 3 11  6]
 [ 1 12  3]
 [ 2  8  8]
 [ 2  9  3]
 [ 2 13  4]
 [ 3 18 12]
 [ 2 10  8]
 [ 1 14  9]
 [ 2  5  3]
 [ 1 14 10]
 [ 1 12  6]
 [ 2  8  6]
 [ 2  3  7]
 [ 4 13  5]
 [ 1 17  6]
 [ 4  2 11]
 [ 3  7  8]
 [ 1 10  9]
 [ 1  7  1]
 [ 2  4  8]
 [ 3 11  9]
 [ 3  7  5]
 [ 4  7  5]
 [ 3  3  9]
 [ 3 17  6]
 [ 1  6  8]
 [ 3

* 将位置数据按照block，subaisle和picker的顺序进行排序

In [5]:
idex=np.lexsort([All_location[:,2],All_location[:,1],-1*All_location[:,0]])
a_sort=All_location[idex,:]

In [6]:
idex1=np.lexsort([picker_location[:,2],picker_location[:,1],-1*picker_location[:,0]])
a_sort1=picker_location[idex1,:]

* 使用切片功能，将每一个block的位置信息存储到数组中

In [7]:
arr1=a_sort[a_sort[:,0]==1]
arr2=a_sort[a_sort[:,0]==2]
arr3=a_sort[a_sort[:,0]==3]
arr4=a_sort[a_sort[:,0]==4]
arr11=a_sort1[a_sort1[:,0]==1]
arr21=a_sort1[a_sort1[:,0]==2]
arr31=a_sort1[a_sort1[:,0]==3]
arr41=a_sort1[a_sort1[:,0]==4]
print arr1
print '-------------'
print arr2
print '-------------'
print arr3
print '-------------'
print arr4

[[ 1  1  0]
 [ 1  1  6]
 [ 1  1 11]
 [ 1  2  0]
 [ 1  2 11]
 [ 1  3  0]
 [ 1  3  2]
 [ 1  3  4]
 [ 1  3  6]
 [ 1  3  9]
 [ 1  3 11]
 [ 1  4  0]
 [ 1  4  2]
 [ 1  4 11]
 [ 1  5  0]
 [ 1  5 10]
 [ 1  5 11]
 [ 1  6  0]
 [ 1  6  7]
 [ 1  6  8]
 [ 1  6 11]
 [ 1  7  0]
 [ 1  7  1]
 [ 1  7 11]
 [ 1  8  0]
 [ 1  8  1]
 [ 1  8 11]
 [ 1  9  0]
 [ 1  9 11]
 [ 1 10  0]
 [ 1 10  6]
 [ 1 10  9]
 [ 1 10 11]
 [ 1 11  0]
 [ 1 11  6]
 [ 1 11 11]
 [ 1 12  0]
 [ 1 12  1]
 [ 1 12  3]
 [ 1 12  6]
 [ 1 12  8]
 [ 1 12 11]
 [ 1 13  0]
 [ 1 13 11]
 [ 1 14  0]
 [ 1 14  9]
 [ 1 14 10]
 [ 1 14 10]
 [ 1 14 11]
 [ 1 15  0]
 [ 1 15  5]
 [ 1 15 11]
 [ 1 16  0]
 [ 1 16 11]
 [ 1 17  0]
 [ 1 17  4]
 [ 1 17  6]
 [ 1 17 11]
 [ 1 18  0]
 [ 1 18 11]]
-------------
[[ 2  1  0]
 [ 2  1  3]
 [ 2  1 11]
 [ 2  2  0]
 [ 2  2 11]
 [ 2  3  0]
 [ 2  3  1]
 [ 2  3  5]
 [ 2  3  7]
 [ 2  3 11]
 [ 2  4  0]
 [ 2  4  8]
 [ 2  4 11]
 [ 2  5  0]
 [ 2  5  3]
 [ 2  5 11]
 [ 2  6  0]
 [ 2  6  9]
 [ 2  6 11]
 [ 2  7  0]
 [ 2  7  1]
 [ 2  7  2]
 

* 首先从最远的block4开始拣货，计算拣货路径和距离

In [8]:
len4=73            #首先穿过整个aisle到达最远的block的前面
tra4=0
Route=[[1,1,0],
       [1,1,11],
       [2,1,0],
       [2,1,11],
      [3,1,0],
      [3,1,13]]
Last_array=arr41[-1,1]   #判断最后一个需要拣货的走道
Last_picker=arr41[-1,2]  #判断最后一个需要拣货通道中最远的货位
for i in range(1,Last_array):       #从第一个通道开始拣货
    if len(arr4[arr4[:,1]==i])>2:   #判断该通道是否需要拣货
        len4=len4+30                #如果需要那么就在总距离上加30
        tra4=tra4+1                 #tra4帮助判断拣货的方向是从前往后，还是从后往前
        if tra4%2==1:               #如果tra4是奇数，那么就从前往后拣货
            Route=np.r_[Route,arr4[arr4[:,1]==i]]
        else:                       #否则，从后往前取拣货
            arr4_sort=arr4[arr4[:,1]==i]
            idex4=np.lexsort([-1*arr4_sort[:,2]])
            Rearr4_sort=arr4_sort[idex4,:]
            Route=np.r_[Route,Rearr4_sort]
    else:                           #如果该通道不需要拣货
        len4=len4+3                 #那么就直走，不进入通道，总距离加3
        Next_picker=Route[-1,:]
        Next_picker[1]=Next_picker[1]+1
        Route=np.vstack((Route,Next_picker))
if Route[-1,2]==0:                  #到最后一个需要拣货的通道，如果是在block的前面，那么就到达最远拣货位然后再返回
    len4=len4+(Last_picker-1)*4+5
    Last_Route=arr4[arr4[:,1]==Last_array]
    Last_Route[-1,2]=0
    Route=np.r_[Route,Last_Route]
else:                              #如果是在block的后面，那么直接穿过该通道，总距离加27
    len4=len4+27
    Last_Route=arr4[arr4[:,1]==Last_array]
    idex41=np.lexsort([-1*arr4_sort[:,2]])
    ReLast_Route=Last_Route[idex41,:]
    Route=np.r_[Route,ReLast_Route]
print len4, Route

490 [[ 1  1  0]
 [ 1  1 11]
 [ 2  1  0]
 [ 2  1 11]
 [ 3  1  0]
 [ 3  1 13]
 [ 4  1  0]
 [ 4  1  5]
 [ 4  1 13]
 [ 4  2 13]
 [ 4  2 11]
 [ 4  2  1]
 [ 4  3  0]
 [ 4  4  0]
 [ 4  5  0]
 [ 4  5  0]
 [ 4  6  0]
 [ 4  6  4]
 [ 4  6  8]
 [ 4  6 13]
 [ 4  7 13]
 [ 4  7 11]
 [ 4  7  5]
 [ 4  7  4]
 [ 4  7  0]
 [ 4  8  0]
 [ 4  8  4]
 [ 4  8 13]
 [ 4  9 13]
 [ 4  9  3]
 [ 4  9  0]
 [ 4 10  0]
 [ 4 10  5]
 [ 4 10 13]
 [ 4 11 13]
 [ 4 11 11]
 [ 4 11  0]
 [ 4 12  0]
 [ 4 12  5]
 [ 4 12 13]
 [ 4 13 13]
 [ 4 13  5]
 [ 4 13  4]
 [ 4 13  0]
 [ 4 14  0]
 [ 4 14 11]
 [ 4 15 13]
 [ 4 15 13]
 [ 4 16 13]
 [ 4 16  2]
 [ 4 16  0]
 [ 4 17  0]
 [ 4 17  9]
 [ 4 17 11]
 [ 4 17  0]]


* 接着我们计算block3的拣货路径和距离，注意是从最右边的需要拣货的通道开始拣货

In [9]:
len3=3
tra3=0
First_array=arr31[-1,1]    #判断最右边的需要拣货的通道
Last_picker=arr31[2,2]
for i in range(First_array,2,-1):
    if len(arr3[arr3[:,1]==i])>2:
        len3=len3+30
        tra3=tra3+1
        if tra3%2==1:
            arr3_sort=arr3[arr3[:,1]==i]
            idex3=np.lexsort([-1*arr3_sort[:,2]])
            Rearr3_sort=arr3_sort[idex3,:]
            Route=np.r_[Route,Rearr3_sort]
        else:
            Route=np.r_[Route,arr3[arr3[:,1]==i]]
    else:
        len3=len3+3
        Next_picker=Route[-1,:]
        Next_picker[1]+=1
        Route=np.vstack((Route,Next_picker))
if Route[-1,2]==0:
    len3=len3+(Last_picker-1)*4+5
    Last_Route=arr3[arr3[:,1]==2]
    Last_Route[-1,2]=0
    Route=np.r_[Route,Last_Route]
else:
    len3=len3+27
    Last_Route=arr3[arr3[:,1]==2]
    idex31=np.lexsort([-1*arr3_sort[:,2]])
    ReLast_Route=Last_Route[idex31,:]
    Route=np.r_[Route,ReLast_Route]
print Route,len3

[[ 1  1  0]
 [ 1  1 11]
 [ 2  1  0]
 [ 2  1 11]
 [ 3  1  0]
 [ 3  1 13]
 [ 4  1  0]
 [ 4  1  5]
 [ 4  1 13]
 [ 4  2 13]
 [ 4  2 11]
 [ 4  2  1]
 [ 4  3  0]
 [ 4  4  0]
 [ 4  5  0]
 [ 4  5  0]
 [ 4  6  0]
 [ 4  6  4]
 [ 4  6  8]
 [ 4  6 13]
 [ 4  7 13]
 [ 4  7 11]
 [ 4  7  5]
 [ 4  7  4]
 [ 4  7  0]
 [ 4  8  0]
 [ 4  8  4]
 [ 4  8 13]
 [ 4  9 13]
 [ 4  9  3]
 [ 4  9  0]
 [ 4 10  0]
 [ 4 10  5]
 [ 4 10 13]
 [ 4 11 13]
 [ 4 11 11]
 [ 4 11  0]
 [ 4 12  0]
 [ 4 12  5]
 [ 4 12 13]
 [ 4 13 13]
 [ 4 13  5]
 [ 4 13  4]
 [ 4 13  0]
 [ 4 14  0]
 [ 4 14 11]
 [ 4 15 13]
 [ 4 15 13]
 [ 4 16 13]
 [ 4 16  2]
 [ 4 16  0]
 [ 4 17  0]
 [ 4 17  9]
 [ 4 17 11]
 [ 4 17  0]
 [ 3 18 13]
 [ 3 18 12]
 [ 3 18  0]
 [ 3 17  0]
 [ 3 17  4]
 [ 3 17  6]
 [ 3 17 13]
 [ 3 16 13]
 [ 3 16  1]
 [ 3 16  0]
 [ 3 15  0]
 [ 3 15  1]
 [ 3 15 13]
 [ 3 14 13]
 [ 3 14  6]
 [ 3 14  0]
 [ 3 13  0]
 [ 3 13  3]
 [ 3 13 13]
 [ 3 12 13]
 [ 3 12  8]
 [ 3 12  4]
 [ 3 12  0]
 [ 3 11  0]
 [ 3 11  1]
 [ 3 11  5]
 [ 3 11  6]
 [ 3 11  9]
 [ 3

* 接着我们计算block2的拣货路径和距离

In [10]:
len2=3
tra2=0
Last_array=arr21[-1,1]
Last_picker=arr21[-1,2]
First_array=Route[-1,:]
First_array[0]-=1
First_array[2]=11
Route=np.row_stack((Route,First_array))
for i in range(3,Last_array):
    if len(arr2[arr2[:,1]==i])>2:
        len2=len2+26
        tra2=tra2+1
        if tra2%2==0:
            Route=np.r_[Route,arr2[arr2[:,1]==i]]
        else:
            arr2_sort=arr2[arr2[:,1]==i]
            idex2=np.lexsort([-1*arr2_sort[:,2]])
            Rearr2_sort=arr2_sort[idex2,:]
            Route=np.r_[Route,Rearr2_sort]
    else:
        len2=len2+3
        Next_picker=Route[-1,:]
        Next_picker[1]+=1
        Route=np.vstack((Route,Next_picker))
if Route[-1,2]==0:
    len2=len2+(Last_picker-1)*4+5
    Last_Route=arr2[arr2[:,1]==Last_array]
    Last_Route[-1,2]=0
    Route=np.r_[Route,Last_Route]
else:
    len2=len2+23
    Last_Route=arr2[arr2[:,1]==Last_array]
    idex21=np.lexsort([-1*arr2_sort[:,2]])
    ReLast_Route=Last_Route[idex21,:]
    Route=np.r_[Route,ReLast_Route]
print len2,Route

377 [[ 1  1  0]
 [ 1  1 11]
 [ 2  1  0]
 [ 2  1 11]
 [ 3  1  0]
 [ 3  1 13]
 [ 4  1  0]
 [ 4  1  5]
 [ 4  1 13]
 [ 4  2 13]
 [ 4  2 11]
 [ 4  2  1]
 [ 4  3  0]
 [ 4  4  0]
 [ 4  5  0]
 [ 4  5  0]
 [ 4  6  0]
 [ 4  6  4]
 [ 4  6  8]
 [ 4  6 13]
 [ 4  7 13]
 [ 4  7 11]
 [ 4  7  5]
 [ 4  7  4]
 [ 4  7  0]
 [ 4  8  0]
 [ 4  8  4]
 [ 4  8 13]
 [ 4  9 13]
 [ 4  9  3]
 [ 4  9  0]
 [ 4 10  0]
 [ 4 10  5]
 [ 4 10 13]
 [ 4 11 13]
 [ 4 11 11]
 [ 4 11  0]
 [ 4 12  0]
 [ 4 12  5]
 [ 4 12 13]
 [ 4 13 13]
 [ 4 13  5]
 [ 4 13  4]
 [ 4 13  0]
 [ 4 14  0]
 [ 4 14 11]
 [ 4 15 13]
 [ 4 15 13]
 [ 4 16 13]
 [ 4 16  2]
 [ 4 16  0]
 [ 4 17  0]
 [ 4 17  9]
 [ 4 17 11]
 [ 4 17  0]
 [ 3 18 13]
 [ 3 18 12]
 [ 3 18  0]
 [ 3 17  0]
 [ 3 17  4]
 [ 3 17  6]
 [ 3 17 13]
 [ 3 16 13]
 [ 3 16  1]
 [ 3 16  0]
 [ 3 15  0]
 [ 3 15  1]
 [ 3 15 13]
 [ 3 14 13]
 [ 3 14  6]
 [ 3 14  0]
 [ 3 13  0]
 [ 3 13  3]
 [ 3 13 13]
 [ 3 12 13]
 [ 3 12  8]
 [ 3 12  4]
 [ 3 12  0]
 [ 3 11  0]
 [ 3 11  1]
 [ 3 11  5]
 [ 3 11  6]
 [ 3 11  9]


* 最后我们计算block3的拣货路径和距离，注意是从最右边的需要拣货的通道开始拣货，并返回到出发点

In [11]:
len1=6
tra1=0
First_array=arr11[-1,1]
Last_picker=arr11[4,2]
for i in range(First_array,3,-1):
    if len(arr1[arr1[:,1]==i])>2:
        len1=len1+26
        tra1=tra1+1
        if tra1%2==1:
            arr1_sort=arr1[arr1[:,1]==i]
            idex1=np.lexsort([-1*arr1_sort[:,2]])
            Rearr1_sort=arr1_sort[idex1,:]
            Route=np.r_[Route,Rearr1_sort]
        else:
            Route=np.r_[Route,arr1[arr1[:,1]==i]]
    else:
        len1=len1+3
        Next_picker=Route[-1,:]
        Next_picker[1]+=1
        Route=np.row_stack((Route,Next_picker))
if Route[-1,2]==0:
    len1=len1+(Last_picker-1)*4+5
    Last_Route=arr1[arr1[:,1]==3]
    Last_Route[-1,2]=0
    Route=np.r_[Route,Last_Route]
else:
    len1=len1+23
    Last_Route=arr1[arr1[:,1]==3]
    idex11=np.lexsort([-1*arr1_sort[:,2]])
    ReLast_Route=Last_Route[idex11,:]
    Route=np.r_[Route,ReLast_Route]
Leave_route=[[1,2,0],
            [1,1,0]]
Route=np.r_[Route,Leave_route]
print Route,len1

[[ 1  1  0]
 [ 1  1 11]
 [ 2  1  0]
 [ 2  1 11]
 [ 3  1  0]
 [ 3  1 13]
 [ 4  1  0]
 [ 4  1  5]
 [ 4  1 13]
 [ 4  2 13]
 [ 4  2 11]
 [ 4  2  1]
 [ 4  3  0]
 [ 4  4  0]
 [ 4  5  0]
 [ 4  5  0]
 [ 4  6  0]
 [ 4  6  4]
 [ 4  6  8]
 [ 4  6 13]
 [ 4  7 13]
 [ 4  7 11]
 [ 4  7  5]
 [ 4  7  4]
 [ 4  7  0]
 [ 4  8  0]
 [ 4  8  4]
 [ 4  8 13]
 [ 4  9 13]
 [ 4  9  3]
 [ 4  9  0]
 [ 4 10  0]
 [ 4 10  5]
 [ 4 10 13]
 [ 4 11 13]
 [ 4 11 11]
 [ 4 11  0]
 [ 4 12  0]
 [ 4 12  5]
 [ 4 12 13]
 [ 4 13 13]
 [ 4 13  5]
 [ 4 13  4]
 [ 4 13  0]
 [ 4 14  0]
 [ 4 14 11]
 [ 4 15 13]
 [ 4 15 13]
 [ 4 16 13]
 [ 4 16  2]
 [ 4 16  0]
 [ 4 17  0]
 [ 4 17  9]
 [ 4 17 11]
 [ 4 17  0]
 [ 3 18 13]
 [ 3 18 12]
 [ 3 18  0]
 [ 3 17  0]
 [ 3 17  4]
 [ 3 17  6]
 [ 3 17 13]
 [ 3 16 13]
 [ 3 16  1]
 [ 3 16  0]
 [ 3 15  0]
 [ 3 15  1]
 [ 3 15 13]
 [ 3 14 13]
 [ 3 14  6]
 [ 3 14  0]
 [ 3 13  0]
 [ 3 13  3]
 [ 3 13 13]
 [ 3 12 13]
 [ 3 12  8]
 [ 3 12  4]
 [ 3 12  0]
 [ 3 11  0]
 [ 3 11  1]
 [ 3 11  5]
 [ 3 11  6]
 [ 3 11  9]
 [ 3

* 得到最终拣货路径和总行走距离

In [12]:
Total_length=len1+len2+len3+len4
print Total_length

1661


* 得到S-shape heuristic总的计算时间

In [13]:
def test(n):
    """Stupid test function"""
    L = []
    for i in range(n):
        L.append(i)
if __name__ == '__main__':
    test_round = 1000
time_cost = timeit.timeit("test(10000)", setup="from __main__ import test", number = test_round)
print "test_case1: ", time_cost/test_round


test_case1:  0.00489349830766
